=== arr588/unidad6-LM/actividad1/ejercicio3.dtd
<!ELEMENT automovil (datos, especificaciones)>
<!ELEMENT datos (marca, modelo, anyo)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT anyo (#PCDATA)>
<!ELEMENT especificaciones (longitud, traccion-delantera*, traccion-trasera*, traccion-4x4*, motor)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT traccion-delantera (#PCDATA)>
<!ELEMENT traccion-trasera (#PCDATA)>
<!ELEMENT traccion-4x4 (#PCDATA)>
<!ELEMENT motor (cilindros, cc, cv)>
<!ELEMENT cilindros (#PCDATA)>
<!ELEMENT cc (#PCDATA)>
<!ELEMENT cv (#PCDATA)>

=== arr588/unidad6-LM/actividad1/ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE automovil SYSTEM "ejercicio3.dtd">
<automovil>
    <datos>
    <marca>Volkswagen</marca>
    <modelo>Corrado</marca>
    <anyo>1989</anyo>
    </datos>
    <especificaciones>
        <longitud>4,05</longitud>
        <traccion-delantera/>
        <motor>
            <cilindros>6</cilindros>
            <cc>3000</cc>
            <cv>190</cv>
        </motor>
    </especificaciones>
</automovil>
