=== arr588/unidad6-LM/actividadesXSD/actividad10/ejercicio2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- Datos -->

    <xs:simpleType name="tipo-nombre">
        <xs:restriction base="xs:string">
            <xs:maxLength value="50"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipo-version">
        <xs:restriction base="xs:byte">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="10"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- XSD -->
    <xs:element name="vehiculos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="vehiculo" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:ID"/>
                            <xs:element name="nombre" type="tipo-nombre"/>
                            <xs:element name="modelo" type="xs:string"/>
                            <xs:element name="version" type="tipo-version"/>
                            <xs:element name="fabricacion">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:choice maxOccurs="2">
                                            <xs:element name="inicio" type="xs:date" minOccurs="1"/>
                                            <xs:element name="fin" type="xs:date" minOccurs="1"/>
                                        </xs:choice>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="modificaciones">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="modificacion" type="xs:string" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== arr588/unidad6-LM/actividadesXSD/actividad10/ejercicio2.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<vehiculos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ejercicio2.xsd">
  <vehiculo>
    <id>veh-1</id>
    <nombre>Count Zero</nombre>
    <modelo>Series I</modelo>
    <version>2</version>
    <fabricacion>
      <inicio>1949-07-21</inicio>
      <fin>1949-08-09</fin>
    </fabricacion>
    <modificaciones>
      <modificacion>Change Engine</modificacion>
      <modificacion>Change pedals</modificacion>
      <modificacion>Change gearbox</modificacion>
      <modificacion>Fit Rollcage</modificacion>
    </modificaciones>
  </vehiculo>
</vehiculos>
