=== arr588/unidad6-LM/actividadesXSD/actividad1/ejercicio4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="filmoteca">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pelicula" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string"/>
                            <xs:element name="anyo" type="xs:positiveInteger"/>
                            <xs:element name="actores">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="actor" minOccurs="0" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== arr588/unidad6-LM/actividadesXSD/actividad1/ejercicio4.xml
<?xml version="1.0" encoding="UTF-8"?>
<filmoteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ejercicio4.xsd">
    <pelicula>
        <titulo>Coherence</titulo>
        <anyo>2013</anyo>
        <actores>
            <actor>Emily Baldoni</actor>
            <actor>Maury Sterling</actor>
        </actores>
    </pelicula>
    <pelicula>
        <titulo>Un día más con vida</titulo>
        <anyo>2018</anyo>
        <actores/>
    </pelicula>
</filmoteca>
