=== arr588/unidad6-LM/XSD/03-esquema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="persona">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre"/>
                <xs:element name="apellidos"/>
                <xs:element name="f_nac">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="dia" type="xs:integer" default="1"/>
                            <xs:element name="mes" type="xs:integer" default="1"/>
                            <xs:element name="anyo" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="activo" fixed="sÃ­"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== arr588/unidad6-LM/XSD/03-ejercicio-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<persona xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="03-esquema.xsd">    
    <nombre>Fermín</nombre>
    <apellidos>Romero de Torres</apellidos>
    <f_nac>
        <dia>24</dia>
        <mes>1</mes>
        <anyo>1898</anyo>
    </f_nac>
    <activo>sí</activo>
</persona>
