=== arr588/unidad6-LM/XSD/14-patterns.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:simpleType name="tipo-patron-A">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{5,8}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipo-patron-B">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{5}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipo-patron-C">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{3}[a-z]{3}"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- que tenga 3 letras mayúsculas o minúsculas de la a a la d, seguido de 2 números -->
    <xs:simpleType name="tipo-patron-D">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Da-d]{3}\d{2}"/>
        </xs:restriction>
    </xs:simpleType>
    <!-- que tenga 3 números de 0 a 5 seguido de una letra minúscula desde a - d -->
    <xs:simpleType name="tipo-patron-E">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-5]{3}[a-d]"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- tenga 3 bloque de 3 números separados por - -->
    <xs:simpleType name="tipo-patron-F">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{3}-\d{3}-\d{3}"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- empiece por una letra y tenga 2 números -->
    <xs:simpleType name="tipo-patron-G">
        <xs:restriction base="xs:string">
            <xs:pattern value="\w\d{2}"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Quiero la palabra LGA, seguido de un guión, seguido de 4 dígitos  -->
    <xs:simpleType name="tipo-patron-H">
        <xs:restriction base="xs:string">
            <xs:pattern value="LGA-\d{4}"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Quiero 1 número - cualquier caracter - 1 letra mayúscula  -->
    <xs:simpleType name="tipo-patron-I">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d.[A-Z]"/>
        </xs:restriction>
    </xs:simpleType>
<!-- Quiero la palabra LGA, seguido de un guión, seguido de 4 dígitos .V y número  -->
    <xs:simpleType name="tipo-patron-J">
        <xs:restriction base="xs:string">
            <xs:pattern value="LGA-\d{4}\.V\d"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- a o b, 1 ó 2, un guión, de 3 a 5 letras -->
    <xs:simpleType name="tipo-patron-K">
        <xs:restriction base="xs:string">
            <xs:pattern value="(a|b)(1|2)-\w{3,5}"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- al menos una a, al menos una b, 0 o muchas c -->
    <xs:simpleType name="tipo-patron-L">
        <xs:restriction base="xs:string">
            <xs:pattern value="a+b+c*"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:element name="patrones">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="patronA" type="tipo-patron-A"/>
                <xs:element name="patronB" type="tipo-patron-B"/>
                <xs:element name="patronC" type="tipo-patron-C"/>
                <xs:element name="patronD" type="tipo-patron-D"/>
                <xs:element name="patronE" type="tipo-patron-E"/>
                <xs:element name="patronF" type="tipo-patron-F"/>
                <xs:element name="patronG" type="tipo-patron-G"/>
                <xs:element name="patronH" type="tipo-patron-H"/>
                <xs:element name="patronI" type="tipo-patron-I"/>
                <xs:element name="patronJ" type="tipo-patron-J"/>
                <xs:element name="patronK" type="tipo-patron-K"/>
                <xs:element name="patronL" type="tipo-patron-L"/>

            </xs:choice>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== arr588/unidad6-LM/XSD/14-patterns.xml
<?xml version="1.0" encoding="UTF-8" ?>
<patrones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="14-patterns.xsd">
    <!-- de 5 a 8 números -->
    <patronA>12345678</patronA>
    <patronA>99999999</patronA>
    <!-- 5 letras mayúsculas -->
    <patronB>LMSGI</patronB>
    <!-- 3 letras mayúsculas seguido de 3 minúsculas -->
    <patronC>ABCdef</patronC>
    <!-- que tenga 3 letras mayúsculas o minúsculas de la a a la d, seguido de 2 números -->
    <patronD>AdC99</patronD>
    <patronD>bBb11</patronD>
    <!-- que tenga 3 números de 0 a 5 seguido de una letra minúscula desde a - d -->
    <patronE>123a</patronE>
    <!-- tenga 3 bloque de 3 números separados por - -->
    <patronF>123-456-789</patronF>
    <!-- empiece por una letra y tenga 2 números -->
    <patronG>c18</patronG>
    <!-- Quiero la palabra LGA, seguido de un guión, seguido de 4 dígitos  -->
    <patronH>LGA-1115</patronH>
    <!-- Quiero 1 número - cualquier caracter - 1 letra mayúscula  -->
    <patronI>3#P</patronI>
    <patronI>9$Q</patronI>
    <!-- Quiero la palabra LGA, seguido de un guión, seguido de 4 dígitos .V y número  -->
    <patronJ>LGA-1115.V3</patronJ>
    <!-- a o b, 1 ó 2, un guión, de 3 a 5 letras -->
    <patronK>a2-aaa</patronK>
    <patronK>b1-ababa</patronK>
    <!-- al menos una a, al menos una b, 0 o muchas c -->
    <patronL>aaabbbbb</patronL>
    <patronL>abcccccc</patronL>
</patrones>
