=== arr588/unidad6-LM/practica6.1/ejercicio2/curriculum.dtd
<!ELEMENT curriculum (datos_personales, datos_contacto, formacion+, idiomas+, experiencia, datos_adicionales)>
<!ELEMENT datos_personales (nombre, apellidos, fecha_nac, lugar_nac, nacionalidad+, identificacion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT fecha_nac (#PCDATA)>
<!ELEMENT lugar_nac (#PCDATA)>
<!ELEMENT nacionalidad (#PCDATA)>
<!ELEMENT identificacion (#PCDATA)>
<!ATTLIST identificacion tipo (nif | nie) "nie">
<!ELEMENT datos_contacto (tipo_via, nombre_via, numero*, portal*, email, telf_fijo*, telf_movil)>
<!ELEMENT tipo_via EMPTY>
<!ATTLIST tipo_via tipo (calle | avenida) "calle">
<!ELEMENT nombre_via (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT portal (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT telf_fijo (#PCDATA)>
<!ELEMENT telf_movil (#PCDATA)>
<!ELEMENT formacion (titulo, lugar_estudio, fecha_inicio*, fecha_fin*)>
<!ATTLIST formacion enCurso (true | false) #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT lugar_estudio (#PCDATA)>
<!ELEMENT fecha_inicio (#PCDATA)>
<!ELEMENT fecha_fin (#PCDATA)>
<!ELEMENT idiomas (idioma, nivel)>
<!ATTLIST idiomas materno (si | no) "no">
<!ELEMENT idioma EMPTY>
<!ATTLIST idioma nombre (espaÃ±ol | ingles | frances | aleman | italiano) #REQUIRED>
<!ELEMENT nivel (#PCDATA)>
<!ELEMENT experiencia (lugar_trabajo, puesto*, empresa, fecha_inicio, fecha_fin)>
<!ELEMENT lugar_trabajo (#PCDATA)>
<!ELEMENT puesto (#PCDATA)>
<!ELEMENT empresa (#PCDATA)>
<!ELEMENT datos_adicionales (#PCDATA | em | strong)*>
<!ELEMENT em (#PCDATA)>
<!ELEMENT strong (#PCDATA)>

=== arr588/unidad6-LM/practica6.1/ejercicio2/curriculum.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html-celia SYSTEM "curriculum.dtd">
<curriculum>
    <datos_personales>
        <nombre></nombre>
        <apellidos></apellidos>
        <fecha_nac></fecha_nac>
        <lugar_nac></lugar_nac>
        <nacionalidad></nacionalidad>
        <identificacion tipo = 'nie'></identificacion>
    </datos_personales>
    <datos_contacto>
        <tipo_via></tipo_via>
        <nombre_via></nombre_via>
        <numero></numero>
        <portal></portal>
        <email></email>
        <telf_fijo></telf_fijo>
        <telf_movil></telf_movil>
    </datos_contacto>
    <formacion enCurso = ''>
        <titulo></titulo>
        <lugar_estudio></lugar_estudio>
        <fecha_inicio></fecha_inicio>
        <fecha_fin></fecha_fin>
    </formacion>
    <idiomas materno = ''>
        <nombre></nombre>
        <nivel></nivel>
    </idiomas>
    <experiencia>
        <lugar_trabajo></lugar_trabajo>
        <puesto></puesto>
        <empresa></empresa>
        <fecha_inicio></fecha_inicio>
        <fecha_fin></fecha_fin>
    </experiencia>
    <datos_adicionales>
        <p></p>
        <em></em>
        <strong></strong>
    </datos_adicionales>
</curriculum>
